name: Servidor GM - Spider Crawler Autônomo

on:
  push:
    paths:
      - 'alvo.txt' # O Actions só acorda quando este arquivo for alterado

jobs:
  crawler-service:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Baixar motor de busca do repositório
      uses: actions/checkout@v4

    - name: Ler URL solicitada pelo Frontend
      id: obter_url
      run: |
        URL_MINERAR=$(cat alvo.txt | xargs)
        echo "URL_INICIAL=$URL_MINERAR" >> $GITHUB_ENV
        echo "Iniciando varredura no alvo: $URL_MINERAR"

    - name: Inicializar ambiente Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar bibliotecas de requisição assíncrona
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp beautifulsoup4

    - name: Executar Spider Rastreamento
      env:
        URL_INICIAL: ${{ env.URL_INICIAL }}
        MAX_PAGINAS: '15'
      run: python robo.py

    # O robô usa o Secret protegido para commitar de volta no repositório público
    - name: Salvar e publicar resultados no repositório
      env:
        GITHUB_TOKEN: ${{ secrets.GM_PAT_TOKEN }} # Puxando a sua variável secreta guardada
      run: |
        git config --global user.name "GM Robot Service"
        git config --global user.email "robo@gmcorporation.com.br"
        git add resultados.json || true
        git commit -m "data: atualizando indices do motor de busca [skip ci]" || true
        git push
